# 서강대학교 전자도서관 크롤링

In [1]:
from bs4 import BeautifulSoup
import requests 
import pandas as pd
import re

In [2]:
book_res = pd.DataFrame(columns=['제목','연도','저자','대출현황','요약'])

In [6]:
page_no = 1
page_url = f'http://kyobobook.sogang.ac.kr/elibrary-front/search/searchList.ink?brcd=&sntnAuthCode=&contentAll=&cttsDvsnCode=&orderByKey=&schClst=all&schDvsn=000&reSch=&ctgrId=&allClstCheck=on&clstCheck=ctts&clstCheck=autr&clstCheck=pbcm&clstCheck=intc_cntt&allDvsnCheck=000&dvsnCheck=001&schTxt=it&reSchTxt=&selViewCnt=20&pageIndex={page_no}&recordCount=20'

In [7]:
req = requests.get(page_url)
content = req.content
soup = BeautifulSoup(content, 'html.parser')

title = [t.text for t in soup.select('li.tit')]
author = [a.contents[0] for a in soup.select('li.writer')]
ymd = [a.contents[-1] for a in soup.select('li.writer')]
use = [u.select('strong')[0].text for u in soup.select('p.use')]
txt = [t.text for t in soup.select('li.txt')]

tmp = pd.DataFrame([title, ymd, author, use, txt], index=['제목','연도','저자','대출현황','요약']).T

book_res = pd.concat([book_res, tmp])

In [41]:
book_res

,제목,연도,저자,대출현황,요약
0,퀴팅,2024-01-17,줄리아 켈러,1/2,"인생을 역주행시킨 이들의 공통점은 바로 ‘퀴팅’이었다!\n사회학, 심리학, 신경과학..."
1,이것이 취업을 위한 백엔드 개발이다 with 자바,2024-01-12,이준형,0/1,백엔드 개발자를 꿈꾸는 분이라면 이런 이야기를 많이 들어 봤을 것입니다.\n“백엔드...
2,어차피 일할 거라면 원하는 일 할게요,2024-01-11,앤가은,0/1,"일은 중요하다. 누구나 돈 많은 백수를 꿈꾸지만, 금수저가 아닌 우리는 먹고살기 위..."
3,요즘 개발자,2023-12-22,임동준,1/1,요즘 개발자’ 성장에 필요한 \nWhat & How 로드맵\n\n개발자로서의 성장에...
4,결국 원하는 것을 얻는 사람들의 비밀,2023-12-19,조이 챈스,0/1,"사람들이 살면서 가장 듣고 싶어 하는 최고의 영향력 강의!\n설득, 부탁, 협상에서..."
5,스토리테크 전쟁,2023-12-04,류현정,0/2,◆ 실리콘밸리 특파원 출신 IT 전문 기자의 인사이트\n◆ KTㆍ네이버ㆍ리디 업계 ...
6,겨울 간식집,2023-11-27,박연준,0/1,시절이 변해도 어김없이 돌아오는 겨울의 풍경들을 모은 《겨울 간식집》이 읻다에서 출...
7,나는 왜 마약 변호사를 하는가,2023-11-27,안준형,0/1,마약은 과연 출구 없는 미로인가?\n미로의 출구를 닫아버리는 것은 누구인가?\n‘마...
8,나의 첫 알고리즘+자료구조 with 파이썬,2023-11-01,코리 알트호프,0/1,컴퓨터 과학은 컴퓨터가 어떻게 작동하는지를 연구하는 학문입니다. 소프트웨어 개발자가...
9,AI 2024 트렌드&활용백과,2023-10-25,김덕진,0/1,절대 놓쳐서는 안 될 2024년 AI 트렌드와 활용법. 10여 년 동안 IT 트렌드...
10,챗GPT와 데이터 분석 with 코드 인터프리터,2023-08-25,김철수,1/1,코드 인터프리터와 함께라면 누구나 데이터 과학자가 될 수 있습니다!\n이 책은 Ch...
11,죄와 벌. 1,2023-07-31,표도르 도스토예프스키,0/1,▶ 자신을 천재로 여긴 러시아의 청년\n이상을 좇는 모든 시대 젊은이의 초상이 되다...
12,죄와 벌. 2,2023-07-31,표도르 도스토예프스키,0/1,"▶ 자신을 천재로 여긴 러시아의 청년,\n이상을 좇는 모든 시대 젊은이의 초상이 되..."
13,나는 앞으로 몇 번의 보름달을 볼 수 있을까,2023-06-28,사카모토 류이치,1/2,"한국, 일본, 중국, 대만 동시 출간!\n방탄소년단 슈가, 윤상, 이준오(캐스커),..."
14,"반도체 전쟁, 칩워의 종말",2023-06-20,"Ghat GPT 저자, 루이스 액설로드 역자",1/1,"『반도체 전쟁, 칩워의 종말 (G2 전쟁의 중심, 세계를 움직이는 반도체)』은 반도..."
15,AI 이후의 세계,2023-05-22,헨리 키신저,1/1,키신저(미국 전 국무장관) × 슈밋(구글 전 CEO) × 허튼로커(MIT 학장)\n...
16,적과 흑,2023-04-27,스탕달,0/1,"제4차 산업혁명 세대를 위한\n진정한 독서의 길,\n세계문학 ‘축역본의 정본’ 시대..."
17,영혼의 설계자,2023-04-13,그레그 호프먼,0/2,나이키 전 최고마케팅책임자 그레그 호프먼(Greg Hoffman)의 저서로 창업주의...
18,챗GPT시대 글쓰기,2023-02-28,이세훈,0/1,시나리오·소설·이력서·광고 카피·블로그 게시글까지 \n아이디어만 있으면 어떤 글이든...
19,디테일의 발견,2023-02-15,생각노트,0/2,일주일에 한 번 돌아오는 온갖 회의에 들어갈 때마다 우리는 머리를 쥐어짠다. 새로운...

# 영풍문고 베스트셀러 다운로드

In [53]:
from selenium import webdriver
from selenium.webdriver.common.by import By

url = 'https://www.ypbooks.co.kr/book_arrange.yp?targetpage=book_week_best&pagetype=5&depth=1'
driver = webdriver.Chrome()
driver.get(url)
driver.find_element(By.XPATH, '//*[@id="rightArea01"]/div[1]/div/dl/dt[5]/span/a').click()

best = pd.read_excel('C:/Users/user/Downloads/BestSeller.xls')

driver.close()  # 셀레니움 세션 종료

In [ ]:
# headless mode

option = webdriver.ChromeOptions()
option.add_argument('headless')

url = 'https://www.ypbooks.co.kr/book_arrange.yp?targetpage=book_week_best&pagetype=5&depth=1'
driver = webdriver.Chrome(options=option)
driver.get(url)

title = driver.find_element(By.XPATH, '//*[@id="rightArea01"]/div[2]/div[2]/ul/li/dl/b/dd[1]/strong[2]').text
print(title)

driver.close()

# 무신사 크롤링

In [195]:
musinsa_result = pd.DataFrame(columns=['제조사','상품명','할인전가격','판매가','만족도'])

max_page = int(soup.select('span.totalPagingNum')[0].text)

if max_page > 400:
    max_page = 400

for page in range(1, max_page+1):
    url = f'''https://www.musinsa.com/categories/item/001005?d_cat_cd=001005&brand=&list_kind=small&sort=pop_category&sub_sort=&page={page}&display_cnt=90&group_sale=&exclusive_yn=&sale_goods=&timesale_yn=&ex_soldout=&plusDeliveryYn=&kids=&color=&price1=&price2=&shoeSizeOption=&tags=&campaign_id=&includeKeywords=&measure='''

    req = requests.get(url)
    content = req.content
    soup = BeautifulSoup(content, 'html.parser')

    brand = [b.text for b in soup.select('p.item_title')]

    name = []

    for n in soup.select('p.list_info'):
        n2 = n.text
        name.append(re.sub('\s+',' ',n2)[1:-1])

    price1 = []
    price2 = []

    for p in soup.select('p.price'):
        p_temp = p.text.split('\n')
        price1.append(p_temp[1])
        price2.append(p_temp[2])

    review = []

    for a in soup.select('div.article_info'):
        # 리뷰가 없는 경우, span.bar 객체가 없습니다
        if a.select('span.bar') == []:
            review.append(float('nan'))
        else:
            # 무신사 리뷰 평점은 span.bar의 길이에 비례
            a2 = a.select('span.bar')[0]['style'][6:]
            review.append(a2)

    musinsa_temp = pd.DataFrame([brand, name, price1, price2, review], 
                                index=['제조사','상품명','할인전가격','판매가','만족도']).T

    def price_change(x):
        if x != x:
            return x
        x2 = re.sub('[ ,원%]+','',x)
        if x2 == '':
            return float('nan')
        else:
            return int(x2)

    musinsa_temp['할인전가격'] = musinsa_temp['할인전가격'].apply(lambda x: price_change(x))
    musinsa_temp['판매가'] = musinsa_temp['판매가'].apply(lambda x: price_change(x))
    musinsa_temp['만족도'] = musinsa_temp['만족도'].apply(lambda x: price_change(x))

    musinsa_result = pd.concat([musinsa_result, musinsa_temp])

IndexError: list index out of range

# 네이버페이 증권 데이터 크롤링

In [187]:
url = 'https://finance.naver.com/sise/sise_rise.naver'

In [192]:
req = requests.get(url)
content = req.content
soup = BeautifulSoup(content, 'html.parser')

table = soup.select('table.type_2')[0]
df = pd.read_html(str(table), index_col=0)
df2 = df[0]
df2.dropna(how='all', inplace=True)

In [222]:
df2

,종목명,현재가,전일비,등락률,거래량,매수호가,매도호가,매수총잔량,매도총잔량,PER,ROE
N,,,,,,,,,,,
1.0,한국패러랠,266.0,50.0,+23.15%,1631228.0,266.0,267.0,146390.0,45045.0,NaN,NaN
2.0,한화갤러리아,1630.0,261.0,+19.07%,68391431.0,1534.0,1535.0,77926.0,113087.0,NaN,NaN
3.0,태림포장,3465.0,520.0,+17.66%,8736580.0,3570.0,3575.0,34102.0,30396.0,19.91,5.25
4.0,비상교육,6280.0,890.0,+16.51%,7042129.0,6510.0,6520.0,25608.0,12115.0,-8.09,-0.51
5.0,디아이,8010.0,850.0,+11.87%,4956813.0,7800.0,7830.0,10688.0,14676.0,34.68,9.97
...,...,...,...,...,...,...,...,...,...,...,...
614.0,SIMPAC,4230.0,5.0,-0.12%,26245.0,4225.0,4235.0,15592.0,1480.0,65.08,13.28
615.0,농심,365500.0,500.0,-0.14%,9777.0,365500.0,366500.0,3095.0,2728.0,12.60,5.17
616.0,GS글로벌,2690.0,5.0,-0.19%,671024.0,2705.0,2715.0,41169.0,47844.0,4.03,19.28
617.0,대양금속,1577.0,3.0,-0.19%,567279.0,1582.0,1586.0,10737.0,21386.0,8.13,NaN
618.0,주연테크,522.0,1.0,-0.19%,81132.0,522.0,526.0,33824.0,45050.0,-4.97,-12.91

# yes24 도서 목록

In [266]:
yes24_res = pd.DataFrame(columns=['제목','URL'])

In [230]:
page_no = 1
url = f'https://www.yes24.com/24/Category/Display/017001054007?PageNumber={page_no}'
req = requests.get(url)
html = req.content
soup = BeautifulSoup(html, 'html.parser')

title = []
book_url = []

for t in soup.select('div.goods_name'):
    title.append(t.select('a')[0].text)
    book_url.append('https://www.yes24.com' + t.select('a')[0]['href'])

temp = pd.DataFrame([title, book_url], index=['제목','URL']).T

yes24_res = pd.concat([yes24_res, temp])

# HRD.net KDT 교육기관 크롤링

In [270]:
url = 'https://www.hrd.go.kr/hrdp/ti/ptiao/PTIAO0300L.do?crseTracseSeSelected=%EB%B9%85%EB%8D%B0%EC%9D%B4%ED%84%B0&ncsSelected=&areaSelected=%EC%A0%84%EA%B5%AD+%3E+%EC%A0%84%EC%B2%B4&searchTotalKeyword=undefined&crseTracseSe=001%7C%EB%B9%85%EB%8D%B0%EC%9D%B4%ED%84%B0&area=00%7C%EC%A0%84%EA%B5%AD+%EC%A0%84%EC%B2%B4&pageId=6&'

In [271]:
req = requests.get(url)
content = req.content
soup = BeautifulSoup(content, 'html.parser')

In [293]:
zone = [re.sub('\s+',' ',z.text) for z in soup.select('p.zone')]
address = [re.sub('\s+',' ',s.text)[1:-1].split(' ( ')[0] for s in soup.select('p.school')]
tel = [re.sub('\s+',' ',s.text)[1:-1].split(' ( ')[1][:-2] for s in soup.select('p.school')]
percentage = [re.sub('\s+','',p.text) for p in soup.select('div.bar')]

s_date = []
e_date = []

for d in soup.select('dl.item.term'):
    temp = re.findall('\d+-\d+-\d+',d.text)
    
    if temp == []:
        continue
        
    else:
        s_date.append(temp[0])
        e_date.append(temp[1])

In [350]:
pd.DataFrame([zone, address, tel, percentage, s_date, e_date], 
             index=['업체명','지역','전화번호','취업률','시작일','종료일']).T

,업체명,지역,전화번호,취업률,시작일,종료일
0,대한상공회의소,부산 중구,02-6050-3930,59.2%,2024-02-20,2024-08-07
1,서울디지털인재개발원,서울 구로구,02-581-2293,63.6%,2024-02-21,2024-08-13
2,기술좋은직업전문학교,부산 북구,051-710-0337,75%,2024-02-21,2024-08-13
3,연세IT미래교육원(구.연세직업전문학교),경기 수원시 장안구,031-256-2662,취업률(해당없음),2024-02-21,2024-08-16
4,글로벌아이티(IT)인재개발학원,서울 관악구,02-6020-0055,83.3%,2024-02-21,2024-08-13
5,그린컴퓨터아카데미 신촌,서울 마포구,02-715-2111,취업률(해당없음),2024-02-22,2024-09-04
6,KH정보교육원 강남지원,서울 강남구,02-1544-9970,취업률(해당없음),2024-02-26,2024-08-30
7,한국소프트웨어인재개발원,서울 서초구,02-2025-8523,90.9%,2024-02-26,2024-08-13
8,더조은컴퓨터아카데미,서울 강남구,02-594-5613,취업률(해당없음),2024-02-26,2024-09-09
9,국제컴퓨터아트학원,서울 강동구,02-479-0654,62.5%,2024-02-26,2024-08-26

In [3]:
import time

In [8]:
driver = webdriver.Chrome()
url = 'https://www.hrd.go.kr/hrdp/ti/ptiao/PTIAO0300L.do?crseTracseSeSelected=%EB%B9%85%EB%8D%B0%EC%9D%B4%ED%84%B0&ncsSelected=&areaSelected=%EC%A0%84%EA%B5%AD+%3E+%EC%A0%84%EC%B2%B4&searchTotalKeyword=undefined&crseTracseSe=001%7C%EB%B9%85%EB%8D%B0%EC%9D%B4%ED%84%B0&area=00%7C%EC%A0%84%EA%B5%AD+%EC%A0%84%EC%B2%B4&pageId=6&'
driver.get(url)

In [10]:
stars = []

for i in range(1,11):
    driver.find_element(By.XPATH, f'//*[@id="contentArea"]/div[6]/ul/li[{i}]/div/p')
    driver.find_element(By.XPATH, f'//*[@id="contentArea"]/div[6]/ul/li[{i}]/div/p/a').click()

    time.sleep(1)
    driver.switch_to.window(driver.window_handles[-1])

    soup = BeautifulSoup(driver.page_source, 'html.parser')
    star = soup.select('span.starRating')[0]['title']
    stars.append(star)

    driver.close()
    time.sleep(.5)
    driver.switch_to.window(driver.window_handles[-1])

In [11]:
stars

['만족도 100점 기준88.1점',
 '만족도 100점 기준70점',
 '만족도 100점 기준100점',
 '만족도 100점 기준68.5점',
 '만족도 100점 기준86.6점',
 '만족도 100점 기준87.5점',
 '만족도 100점 기준68.2점',
 '만족도 100점 기준84.2점',
 '만족도 100점 기준92.9점',
 '만족도 100점 기준90.5점']

In [ ]:
# driver.quit()

In [66]:
import pandas as pd
import re
from bs4 import BeautifulSoup
import requests

In [67]:
riss_res = pd.DataFrame(columns=['제목','본문','저자','기관','연도','학위'])

for istartcount in range(0,31,10):
    '''
    query: 검색어
    pyear: 검색할 연도
    istartcount: 해당 번호의 자료부터 검색
    '''
    query = '정서조절'
    pyear = 2023
    url = f'https://www.riss.kr/search/Search.do?isDetailSearch=N&searchGubun=true&viewYn=OP&queryText=&strQuery=%EC%A0%95%EC%84%9C%EC%A1%B0%EC%A0%88&exQuery=pyear%3A{pyear}%E2%97%88&exQueryText=%EB%B0%9C%ED%96%89%EC%97%B0%EB%8F%84+%5B2023%5D%40%40pyear%3A2023%E2%97%88&order=%2FDESC&onHanja=false&strSort=RANK&p_year1=&p_year2=&iStartCount={istartcount}&orderBy=&mat_type=&mat_subtype=&fulltext_kind=&t_gubun=&learning_type=&ccl_code=&inside_outside=&fric_yn=&db_type=&image_yn=&gubun=&kdc=&ttsUseYn=&l_sub_code=&fsearchMethod=search&sflag=1&isFDetailSearch=N&pageNumber=1&resultKeyword=%EC%A0%95%EC%84%9C%EC%A1%B0%EC%A0%88&fsearchSort=&fsearchOrder=&limiterList=&limiterListText=&facetList=&facetListText=&fsearchDB=&icate=bib_t&colName=bib_t&pageScale=10&isTab=Y&regnm=&dorg_storage=&language=&language_code=&clickKeyword=&relationKeyword=&query={query}'

    req = requests.get(url).content
    soup = BeautifulSoup(req, 'html.parser')

    title = [t.text for t in soup.select('p.title')][11:]
    etc = [e.text.split('\n')[1:-1] for e in soup.select('p.etc')]
    abst = []

    for c in soup.select('div.cont.ml60'):
        if c.select('p.preAbstract') == []:
            abst.append('')
        else:
            abst.append(c.select('p.preAbstract')[0].text)

    riss_temp = pd.DataFrame([title, abst], index=['제목','본문']).T
    riss_temp2 = pd.DataFrame(etc, columns=['저자','기관','연도','학위'])
    riss_temp3 = pd.concat([riss_temp, riss_temp2], axis=1)
    riss_res = pd.concat([riss_res, riss_temp3])

In [80]:
from selenium import webdriver
from selenium.webdriver.common.by import By

driver = webdriver.Chrome()
driver.get(url)

In [84]:
# 연관 검색어
related_keyword = driver.find_element(By.XPATH, '//*[@id="relatedKeyword"]').text
related_keyword = related_keyword.split()

In [102]:
# 많이 본 자료
recommend_content_list = []

recommend_content = driver.find_element(By.XPATH, '//*[@id="recommendContentByKeyword"]/ul[1]')
recommend_content_list += recommend_content.text.split('\n')

driver.find_element(By.XPATH, '//*[@id="recommendContentByKeyword"]/ul[2]/li[2]/a').click()

recommend_content = driver.find_element(By.XPATH, '//*[@id="recommendContentByKeyword"]/ul[1]')
recommend_content_list += recommend_content.text.split('\n')

In [104]:
driver.quit()

In [207]:
import time

In [234]:
url = 'https://www.riss.kr/link?id=T13700539'

driver = webdriver.Chrome()
driver.get(url)

time.sleep(1)
soup = BeautifulSoup(driver.page_source, 'html.parser')

In [235]:
riss_res = pd.DataFrame(columns=['제목','본문','저자','기관','연도','학위'])

title = re.sub('\s+',' ',soup.select('h3.title')[0].text)
text = soup.select('div.text')[1].text
author = re.sub('\s+',' ',soup.select('a.instituteInfo')[0].text)[1:-1]
inst = soup.select('div.infoDetailL')[0].select('div')[1]
inst2 = re.findall('\S+',inst.text)[2]
year = re.findall('\S+',inst.text)[-1]
lev = soup.select('div.infoDetailL')[0].select('p')[2].text
lev = re.findall('\([가-힣]+\)',lev)[0][1:-1]

temp = pd.DataFrame([title, text, author, inst2, year, lev], index=['제목','본문','저자','기관','연도','학위']).T
riss_res = pd.concat([riss_res, temp])

In [236]:
riss_res

,제목,본문,저자,기관,연도,학위
0,우울과 충동성이 비행청소년의 자살생각 및 자살시도에 미치는 영향 = The effe...,\nThis study was to investigate the relations ...,김은진,대구가톨릭대학교,2015,석사

In [237]:
driver.quit()